name: CI
on:
  push:
    branches:
      - master
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Build app
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleRelease

      # Sign APK and create release for tags

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Sign APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Clean up build artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -e
          mv app/build/outputs/apk/release/app-release-unsigned-signed.apk mensa-viewer-v${{ env.VERSION_TAG }}.apk
          sha=`sha256sum mensa-viewer-v${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_SHA=$sha" >> $GITHUB_ENV
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Version ${{ env.VERSION_TAG }}
          body: |
            ---
            ### Checksum:
            SHA-256: ${{ env.APK_SHA }}
          files: |
            mensa-viewer-v${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}